/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "帕帕尼的小站",
  "url": "https://roboppn.top",
  "baseUrl": "/",
  "favicon": "img/PPN.png",
  "organizationName": "RoboPPN",
  "projectName": "blog",
  "tagline": "积跬步成千里，积小流成江海",
  "themeConfig": {
    "image": "img/logo.png",
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "logo": {
        "alt": "帕帕尼",
        "src": "img/PPN.png",
        "srcDark": "img/PPN.png"
      },
      "hideOnScroll": true,
      "items": [
        {
          "label": "📑笔记",
          "position": "right",
          "to": "docs/note-introduction/"
        },
        {
          "label": "📘博客",
          "position": "right",
          "to": "blog"
        },
        {
          "label": "🤖项目",
          "position": "right",
          "to": "project"
        },
        {
          "label": "更多",
          "position": "right",
          "items": [
            {
              "label": "归档",
              "to": "blog/archive"
            },
            {
              "label": "资源",
              "to": "resource"
            },
            {
              "label": "友链",
              "to": "friends"
            }
          ]
        },
        {
          "href": "https://github.com/RoboPPN/PPN-Blog",
          "className": "header-github-link",
          "position": "right"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "学习",
          "items": [
            {
              "label": "博客",
              "to": "blog"
            },
            {
              "label": "归档",
              "to": "blog/archive"
            },
            {
              "label": "技术笔记",
              "to": "docs/skill"
            },
            {
              "label": "实战项目",
              "to": "project"
            }
          ]
        },
        {
          "title": "社交媒体",
          "items": [
            {
              "label": "关于我",
              "to": "/about"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/disnox"
            },
            {
              "label": "bilbil",
              "href": "https://space.bilibili.com/511798206?spm_id_from=333.1007.0.0"
            },
            {
              "label": "CSDN",
              "href": "https://blog.csdn.net/m0_47339333?spm=1000.2115.3001.5343"
            },
            {
              "label": "知乎",
              "href": "https://www.zhihu.com/people/chui-zi-26-38"
            }
          ]
        },
        {
          "title": "更多",
          "items": [
            {
              "label": "友链",
              "position": "right",
              "to": "friends"
            },
            {
              "label": "导航",
              "position": "right",
              "to": "resource"
            },
            {
              "html": "<a href=\"https://docusaurus.io/zh-CN/\" target=\"_blank\"><img style=\"height:50px;margin-top:0.5rem\" src=\"/img/buildwith.png\" /><a/>"
            }
          ]
        }
      ],
      "copyright": "本站所有内容遵循<a href=\"https://creativecommons.org/licenses/by/4.0/deed.zh\" >CC BY-NC 4.0</a>开源协议，仅限非商业性使用，转载请注明出处</p><p>Copyright © 2022 - PRESENT 帕帕尼 Built with Docusaurus.</p>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000",
          "backgroundColor": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "php",
        "rust",
        "toml"
      ],
      "defaultLanguage": "javascript",
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "algolia": {
      "appId": "KB96Z4PFJM",
      "apiKey": "00e9d782a3f2d712b1fe0d7907716ac7",
      "indexName": "ppn_index",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "zoom": {
      "selector": ".markdown :not(em) > img",
      "background": {
        "light": "rgb(255, 255, 255)",
        "dark": "rgb(50, 50, 50)"
      },
      "config": {}
    },
    "giscus": {
      "repo": "disnox/disnox_blog",
      "repoId": "R_kgDOIS7BTg",
      "category": "General",
      "categoryId": "DIC_kwDOIS7BTs4CSN3O",
      "theme": "light",
      "darkTheme": "dark"
    },
    "liveCodeBlock": {
      "playgroundPosition": "top"
    },
    "socials": {
      "github": "https://github.com/disnox",
      "blibli": "https://space.bilibili.com/511798206?spm_id_from=333.1007.0.0",
      "zhihu": "https://www.zhihu.com/people/chui-zi-26-38",
      "csdn": "https://blog.csdn.net/m0_47339333?spm=1000.2115.3001.5343",
      "qq": "https://www.helloimg.com/image/ZV1U6u",
      "wx": "http://n0i.cn/1DmzeU",
      "cloudmusic": "https://music.163.com/#/user/home?id=3906202648"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": []
  },
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "帕帕尼的个人博客"
      }
    }
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "path": "docs",
          "sidebarPath": "sidebars.js",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": false,
        "theme": {
          "customCss": [
            "/home/agx-ppn/My github repository/PPN-Blog/src/css/custom.scss"
          ]
        },
        "sitemap": {
          "changefreq": "daily",
          "priority": 0.5
        },
        "gtag": {
          "trackingID": "G-S4SD5NXWXF",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-image-zoom",
    "docusaurus-plugin-sass",
    "/home/agx-ppn/My github repository/PPN-Blog/src/plugin/plugin-baidu-tongji",
    "/home/agx-ppn/My github repository/PPN-Blog/src/plugin/plugin-baidu-push",
    [
      "/home/agx-ppn/My github repository/PPN-Blog/src/plugin/plugin-content-blog",
      {
        "path": "blog",
        "editLocalizedFiles": false,
        "blogDescription": "帕帕尼的个人博客",
        "blogSidebarCount": 10,
        "blogSidebarTitle": "Blogs",
        "postsPerPage": 10,
        "showReadingTime": true,
        "feedOptions": {
          "type": "all",
          "title": "帕帕尼",
          "copyright": "Copyright © 2024 帕帕尼 Built with Docusaurus.<p><a href=\"http://beian.miit.gov.cn/\" class=\"footer_lin\">CC BY-NC 4.0</a></p>"
        }
      }
    ],
    [
      "@docusaurus/plugin-ideal-image",
      {
        "disableInDev": false
      }
    ],
    [
      "@docusaurus/plugin-pwa",
      {
        "debug": true,
        "offlineModeActivationStrategies": [
          "appInstalled",
          "standalone",
          "queryString"
        ],
        "pwaHead": [
          {
            "tagName": "link",
            "rel": "icon",
            "href": "/img/logo.png"
          },
          {
            "tagName": "link",
            "rel": "manifest",
            "href": "/manifest.json"
          },
          {
            "tagName": "meta",
            "name": "theme-color",
            "content": "rgb(51 139 255)"
          }
        ]
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "en",
      "zh-CN"
    ],
    "localeConfigs": {
      "en": {
        "htmlLang": "en-GB",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "baseUrlIssueBanner": true,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
